const {Builder, By, Key} = require('selenium-webdriver');

describe('Tests', function() {
  it('All Tests', async function() {
    const driver = await new Builder().forBrowser('chrome').build();
    await driver.manage().window().maximize();

    await driver.get('https://ruslanpleskun.github.io/cstd-pleskunruslan-2122/');
    await driver.findElement(By.id('season')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('homes')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('character-profiles')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('homes')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('webshops')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('homes')).click();
    await driver.sleep(3000);
    await driver.navigate().refresh();
    await driver.findElement(By.id('season')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('character-profiles')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('webshops')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('homes')).click();
    await driver.sleep(3000);
    await driver.navigate().refresh();

    await driver.findElement(By.id('homes')).click();
    await driver.findElement(By.id('season')).click();
    await driver.sleep(3000);
    await driver.findElement(By.css("a[title='Rick and Morty']")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.navigate().refresh();
    await driver.findElement(By.linkText('United States')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.navigate().refresh();
    await driver.findElement(By.linkText('Cartoon Network')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.linkText('Adult Swim')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.linkText('Pilot')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.navigate().refresh();
    await driver.findElement(By.css(".next")).click();
    await driver.sleep(3000);
    await driver.findElement(By.css(".prev")).click();
    await driver.sleep(3000);
    await driver.findElement(By.css('video')).click();
    await driver.sleep(10000);
    await driver.findElement(By.css('video')).click();
    await driver.sleep(3000);
    await driver.findElement(By.xpath("//div[@class='video-list']//video[contains(@src,'vid-3.mp4')]")).click();
    await driver.sleep(3000);
    await driver.findElement(By.css('video')).click();
    await driver.sleep(5000);
    await driver.findElement(By.xpath("//div[@class='video-list']//video[contains(@src,'vid-2.mp4')]")).click();
    await driver.sleep(3000);
    await driver.findElement(By.css('video')).click();
    await driver.sleep(5000);
    await driver.findElement(By.xpath("//div[@class='video-list']//video[contains(@src,'vid-4.mp4')]")).click();
    await driver.sleep(3000);
    await driver.findElement(By.css('video')).click();
    await driver.sleep(5000);
    await driver.findElement(By.xpath("//div[@class='video-list']//video[contains(@src,'vid-11.mp4')]")).click();
    await driver.sleep(3000);
    await driver.findElement(By.css('video')).click();
    await driver.sleep(5000);
    await driver.findElement(By.xpath("//div[@class='video-list']//video[contains(@src,'vid-8.mp4')]")).click();
    await driver.sleep(3000);
    await driver.findElement(By.css('video')).click();
    await driver.sleep(5000);
    await driver.findElement(By.xpath("//div[@class='video-list']//video[contains(@src,'vid-5.mp4')]")).click();
    await driver.sleep(3000);
    await driver.findElement(By.css('video')).click();
    await driver.sleep(5000);
    await driver.findElement(By.css('video')).click();

    await driver.findElement(By.id('homes')).click();
    await driver.findElement(By.id('webshops')).click();
    await driver.sleep(3000);
    await driver.findElement(By.css('section:nth-of-type(1) > .order-button')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.sleep(3000);
    await driver.navigate().refresh();
    await driver.findElement(By.css("section:nth-of-type(2) > .order-button")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.css('section:nth-of-type(3) > .order-button')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.sleep(3000);
    await driver.findElement(By.css("section:nth-of-type(4) > .order-button")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.css('section:nth-of-type(5) > .order-button')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.sleep(3000);
    await driver.navigate().refresh();
    await driver.findElement(By.css("section:nth-of-type(6) > .order-button")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.css('section:nth-of-type(7) > .order-button')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.sleep(3000);
    await driver.findElement(By.css("section:nth-of-type(8) > .order-button")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.css('section:nth-of-type(9) > .order-button')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.navigate().refresh();
    await driver.sleep(3000);

    await driver.quit();
  });
});
