const {Builder, By, Key} = require('selenium-webdriver');

describe('Tests', function() {
  it('All Tests', async function() {
    const driver = await new Builder().forBrowser('chrome').build();
    await driver.manage().window().maximize();

    await driver.get('https://ruslanpleskun.github.io/cstd-pleskunruslan-2122/');
    await driver.findElement(By.id('season')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('homes')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('character-profiles')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('homes')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('webshops')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('homes')).click();
    await driver.sleep(3000);
    await driver.navigate().refresh();
    await driver.findElement(By.id('season')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('character-profiles')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('webshops')).click();
    await driver.sleep(3000);
    await driver.findElement(By.id('homes')).click();
    await driver.sleep(3000);
    await driver.navigate().refresh();

    await driver.findElement(By.id('homes')).click();
    await driver.findElement(By.id('season')).click();
    await driver.sleep(3000);
    await driver.findElement(By.css("a[title='Rick and Morty']")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.navigate().refresh();
    await driver.findElement(By.linkText('United States')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.navigate().refresh();
    await driver.findElement(By.css("a[title='Cartoon Network']")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.css("a[title='Adult Swim']")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.css("a[title='Pilot (Rick and Morty)']")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.navigate().refresh();
    await driver.findElement(By.css(".next")).click();
    await driver.sleep(3000);
    await driver.findElement(By.css(".prev")).click();
    await driver.sleep(3000);
    await driver.findElement(By.css('video')).click();
    await driver.sleep(10000);
    await driver.findElement(By.css('video')).click();
    await driver.sleep(3000);

    await driver.findElement(By.id('homes')).click();
    await driver.findElement(By.id('webshops')).click();
    await driver.sleep(3000);
    await driver.findElement(By.css('section:nth-of-type(1) > .order-button')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.sleep(3000);
    await driver.navigate().refresh();
    await driver.findElement(By.css("section:nth-of-type(2) > .order-button")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.css('section:nth-of-type(3) > .order-button')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.sleep(3000);
    await driver.findElement(By.css("section:nth-of-type(4) > .order-button")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.css('section:nth-of-type(5) > .order-button')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.sleep(3000);
    await driver.navigate().refresh();
    await driver.findElement(By.css("section:nth-of-type(5) > .order-button")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.css('section:nth-of-type(7) > .order-button')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.sleep(3000);
    await driver.findElement(By.css("section:nth-of-type(8) > .order-button")).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.findElement(By.css('section:nth-of-type(9) > .order-button')).click();
    await driver.sleep(3000);
    await driver.navigate().back();
    await driver.navigate().refresh();
    await driver.sleep(3000);

    await driver.quit();
  });
});
