name: BuildAndTest
on:
  push:
    branches: [ feature/pleskunruslan/develop ]
  pull_request:
    branches: [ develop ]
jobs:
  tests:
    name: Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          npm ci
          npm install selenium-webdriver
          npm install -g chromedriver
          npm install mocha
          npm install mochawesome
      - name: Run Tests
        run: npm test
